insert into author (age, name, genre, id) values (23, "Mark Janel", "Anthology", 1);
insert into author (age, name, genre, id) values (43, "Olivia Goy", "Horror", 2);
insert into author (age, name, genre, id) values (51, "Quartis Young", "Anthology", 3);
insert into author (age, name, genre, id) values (34, "Joana Nimar", "History", 4);
insert into author (age, name, genre, id) values (44, "Kym Less", "Anthology", 5);
insert into book (name, isbn, title, price, id) values ("Joana Nimar", "001-JN", "A History of Ancient Prague", 42, 1);
insert into book (name, isbn, title, price, id) values ("Joana Nimar", "002-JN", "A People's History", 40, 2);
insert into book (name, isbn, title, price, id) values ("Mark Janel", "001-MJ", "The Beatles Anthology", 42, 3);
insert into book (name, isbn, title, price, id) values ("Olivia Goy", "001-OG", "Carrie", 42, 4);
insert into book (name, isbn, title, price, id) values ("Quartis Young", "001-QY", "War Anthology", 42, 5);
insert into book (name, isbn, title, price, id) values ("Mark Janel", "002-MJ", "100 Days", 40, 6);
insert into book (name, isbn, title, price, id) values ("Kim Less", "001-KL", "Modern Anthology", 42, 7);
