INSERT INTO `db_tennis`.`tournament` (`id`, `name`, `version`) VALUES ('1', 'Tournament: 1', '0');
INSERT INTO `db_tennis`.`tournament` (`id`, `name`, `version`) VALUES ('2', 'Tournament: 2', '0');
INSERT INTO `db_tennis`.`tournament` (`id`, `name`, `version`) VALUES ('3', 'Tournament: 3', '0');
INSERT INTO `db_tennis`.`tournament` (`id`, `name`, `version`) VALUES ('4', 'Tournament: 4', '0');

INSERT INTO `db_tennis`.`tennis_player` (`id`, `name`, `version`, `tournament_id`) VALUES ('1', 'Player: 1', '0', '1');
INSERT INTO `db_tennis`.`tennis_player` (`id`, `name`, `version`, `tournament_id`) VALUES ('2', 'Player: 2', '0', '1');
INSERT INTO `db_tennis`.`tennis_player` (`id`, `name`, `version`, `tournament_id`) VALUES ('3', 'Player: 3', '0', '1');
INSERT INTO `db_tennis`.`tennis_player` (`id`, `name`, `version`, `tournament_id`) VALUES ('4', 'Player: 4', '0', '1');
INSERT INTO `db_tennis`.`tennis_player` (`id`, `name`, `version`, `tournament_id`) VALUES ('5', 'Player: 5', '0', '1');
INSERT INTO `db_tennis`.`tennis_player` (`id`, `name`, `version`, `tournament_id`) VALUES ('6', 'Player: 6', '0', '2');
INSERT INTO `db_tennis`.`tennis_player` (`id`, `name`, `version`, `tournament_id`) VALUES ('7', 'Player: 7', '0', '2');
INSERT INTO `db_tennis`.`tennis_player` (`id`, `name`, `version`, `tournament_id`) VALUES ('8', 'Player: 8', '0', '2');
INSERT INTO `db_tennis`.`tennis_player` (`id`, `name`, `version`, `tournament_id`) VALUES ('9', 'Player: 9', '0', '2');
INSERT INTO `db_tennis`.`tennis_player` (`id`, `name`, `version`, `tournament_id`) VALUES ('10', 'Player: 10', '0', '2');
INSERT INTO `db_tennis`.`tennis_player` (`id`, `name`, `version`, `tournament_id`) VALUES ('11', 'Player: 11', '0', '2');
INSERT INTO `db_tennis`.`tennis_player` (`id`, `name`, `version`, `tournament_id`) VALUES ('12', 'Player: 12', '0', '2');
INSERT INTO `db_tennis`.`tennis_player` (`id`, `name`, `version`, `tournament_id`) VALUES ('13', 'Player: 13', '0', '3');
INSERT INTO `db_tennis`.`tennis_player` (`id`, `name`, `version`, `tournament_id`) VALUES ('14', 'Player: 14', '0', '3');
INSERT INTO `db_tennis`.`tennis_player` (`id`, `name`, `version`, `tournament_id`) VALUES ('15', 'Player: 15', '0', '3');
INSERT INTO `db_tennis`.`tennis_player` (`id`, `name`, `version`, `tournament_id`) VALUES ('16', 'Player: 16', '0', '3');
INSERT INTO `db_tennis`.`tennis_player` (`id`, `name`, `version`, `tournament_id`) VALUES ('17', 'Player: 17', '0', '4');
INSERT INTO `db_tennis`.`tennis_player` (`id`, `name`, `version`, `tournament_id`) VALUES ('18', 'Player: 18', '0', '4');