INSERT INTO `db_tennis`.`tournaments` (`id`, `tournament_name`) VALUES ('1', 'US Open');
INSERT INTO `db_tennis`.`tournaments` (`id`, `tournament_name`) VALUES ('2', 'Wimbledon');
INSERT INTO `db_tennis`.`tournaments` (`id`, `tournament_name`) VALUES ('3', 'Roland Garros');
INSERT INTO `db_tennis`.`tournaments` (`id`, `tournament_name`) VALUES ('4', 'AU Open');
INSERT INTO `db_tennis`.`players` (`id`, `player_name`, `player_rank`, `tournament_id`) VALUES ('1', 'Rafael Nadal', '1', '3');
INSERT INTO `db_tennis`.`players` (`id`, `player_name`, `player_rank`, `tournament_id`) VALUES ('2', 'Roger Federer', '2', null);
INSERT INTO `db_tennis`.`players` (`id`, `player_name`, `player_rank`, `tournament_id`) VALUES ('3', 'Roger Federer ', '2', '2');
INSERT INTO `db_tennis`.`players` (`id`, `player_name`, `player_rank`, `tournament_id`) VALUES ('4', 'Novak Djokovic', '3', '1');
INSERT INTO `db_tennis`.`players` (`id`, `player_name`, `player_rank`, `tournament_id`) VALUES ('5', 'Novak Djokovic', '3', '2');
INSERT INTO `db_tennis`.`players` (`id`, `player_name`, `player_rank`, `tournament_id`) VALUES ('6', 'Alexander Zverev', '4', null);
INSERT INTO `db_tennis`.`players` (`id`, `player_name`, `player_rank`, `tournament_id`) VALUES ('7', 'Marin Cilic', '5', '3');
INSERT INTO `db_tennis`.`players` (`id`, `player_name`, `player_rank`, `tournament_id`) VALUES ('8', 'John Isner', '6', '3');
INSERT INTO `db_tennis`.`players` (`id`, `player_name`, `player_rank`, `tournament_id`) VALUES ('9', 'Grigor Dimitrov', '7', '3');
INSERT INTO `db_tennis`.`players` (`id`, `player_name`, `player_rank`, `tournament_id`) VALUES ('10', 'David Goffin', '8', '3');
INSERT INTO `db_tennis`.`players` (`id`, `player_name`, `player_rank`, `tournament_id`) VALUES ('11', 'Ferdando Verdasco', '9', null);
INSERT INTO `db_tennis`.`players` (`id`, `player_name`, `player_rank`, `tournament_id`) VALUES ('12', 'Marius Copil', '10', null);
