INSERT INTO tournament (id, name) VALUES (1, 'Mercedes Cup');
INSERT INTO tournament (id, name) VALUES (2, 'Monte Carlo');
INSERT INTO tournament (id, name) VALUES (3, 'Sofia Open');
INSERT INTO tournament (id, name) VALUES (4, 'Hamburg Open');
INSERT INTO tournament (id, name) VALUES (5, 'Hungarian Open');
INSERT INTO tournament (id, name) VALUES (6, 'Barcelon Open');
INSERT INTO tournament (id, name) VALUES (7, 'Madrid Open');
INSERT INTO tennis_player (id, name, tournament_id) VALUES (1, 'Rafael Nadal', 1);
INSERT INTO tennis_player (id, name, tournament_id) VALUES (2, 'Roger Federer', 1);
INSERT INTO tennis_player (id, name, tournament_id) VALUES (3, 'David Ferer', 2);
INSERT INTO tennis_player (id, name, tournament_id) VALUES (4, 'Andy Murray', 2);
INSERT INTO tennis_player (id, name, tournament_id) VALUES (5, 'Del Potro', 2);
INSERT INTO tennis_player (id, name, tournament_id) VALUES (6, 'Novak D', 3);
INSERT INTO tennis_player (id, name, tournament_id) VALUES (7, 'Marian Cilic', 3);
INSERT INTO tennis_player (id, name, tournament_id) VALUES (8, 'Milos Raonic', 3);
INSERT INTO tennis_player (id, name, tournament_id) VALUES (9, 'Borna Coric', 3);
INSERT INTO tennis_player (id, name, tournament_id) VALUES (10, 'Fabio Fognini', 4);
INSERT INTO tennis_player (id, name, tournament_id) VALUES (11, 'Karen Khachanov', 4);
INSERT INTO tennis_player (id, name, tournament_id) VALUES (12, 'Guido Pella', 5);
INSERT INTO tennis_player (id, name, tournament_id) VALUES (13, 'Denis Shapovalov', 5);
INSERT INTO tennis_player (id, name, tournament_id) VALUES (14, 'Alex de Minaur', 5);
INSERT INTO tennis_player (id, name, tournament_id) VALUES (15, 'Lucas Pouille', 5);
INSERT INTO tennis_player (id, name, tournament_id) VALUES (16, 'Taylor Fritz', 6);
INSERT INTO tennis_player (id, name, tournament_id) VALUES (17, 'Jeremy Chardy', 6);
INSERT INTO tennis_player (id, name, tournament_id) VALUES (18, 'Richard Gasquet', 7);
INSERT INTO tennis_player (id, name, tournament_id) VALUES (19, 'Radu Albot', 7);
INSERT INTO tennis_player (id, name, tournament_id) VALUES (20, 'Hubert Hurkacz', 7);