insert into author (age, name, genre, id) values (23, "Mark Janel", "Anthology", 1);
insert into author (age, name, genre, id) values (43, "Olivia Goy", "Horror", 2);
insert into author (age, name, genre, id) values (51, "Quartis Young", "Anthology", 3);
insert into author (age, name, genre, id) values (34, "Joana Nimar", "History", 4);
insert into author (age, name, genre, id) values (37, "Larisa Tomay", "History", 5);
insert into book (isbn, title, price, author_id, id) values ("001-JN", "A History of Ancient Prague", 34, 4, 1);
insert into book (isbn, title, price, author_id, id) values ("002-JN", "A People's History", 44, 4, 2);
insert into book (isbn, title, price, author_id, id) values ("001-MJ", "The Beatles Anthology", 30, 1, 3);
insert into book (isbn, title, price, author_id, id) values ("001-OG", "Carrie", 33, 2, 4);
insert into book (isbn, title, price, author_id, id) values ("001-LT", "Ghost Soldiers", 41, 5, 5);
insert into book (isbn, title, price, author_id, id) values ("002-LT", "Sapiens", 29, 5, 6);
