INSERT INTO `players_db`.`player` (`id`, `age`, `name`, `version`) VALUES ('1', '31', 'Novak Djokovic', 0);
INSERT INTO `players_db`.`player` (`id`, `age`, `name`, `version`) VALUES ('2', '32', 'Rafael Nadal', 0);
INSERT INTO `players_db`.`player` (`id`, `age`, `name`, `version`) VALUES ('3', '37', 'Roger Federer', 0);
INSERT INTO `players_db`.`player` (`id`, `age`, `name`, `version`) VALUES ('4', '21', 'Alexander Zverev', 0);
INSERT INTO `players_db`.`player` (`id`, `age`, `name`, `version`) VALUES ('5', '30', 'Juan Martin del Potro', 0);
INSERT INTO `players_db`.`player` (`id`, `age`, `name`, `version`) VALUES ('6', '32', 'Kevin Anderson', 0);
INSERT INTO `players_db`.`player` (`id`, `age`, `name`, `version`) VALUES ('7', '30', 'Marin Cilic', 0);
INSERT INTO `players_db`.`player` (`id`, `age`, `name`, `version`) VALUES ('8', '25', 'Dominic Thiem', 0);
INSERT INTO `players_db`.`player` (`id`, `age`, `name`, `version`) VALUES ('9', '29', 'Kei Nishikori', 0);
INSERT INTO `players_db`.`player` (`id`, `age`, `name`, `version`) VALUES ('10', '33', 'John Isner', 0);
