INSERT INTO tournament (id, name) VALUES (1, 'Mercedes Cup');
INSERT INTO tournament (id, name) VALUES (2, 'Monte Carlo');
INSERT INTO tournament (id, name) VALUES (3, 'Sofia Open');
INSERT INTO tournament (id, name) VALUES (4, 'Hamburg Open');
INSERT INTO tournament (id, name) VALUES (5, 'Hungarian Open');
INSERT INTO tournament (id, name) VALUES (6, 'Barcelon Open');
INSERT INTO tournament (id, name) VALUES (7, 'Madrid Open');
INSERT INTO tennis_player (id, name, atprank, tournament_id) VALUES (1, 'Rafael Nadal', 1, 1);
INSERT INTO tennis_player (id, name, atprank, tournament_id) VALUES (2, 'Roger Federer', 2, 1);
INSERT INTO tennis_player (id, name, atprank, tournament_id) VALUES (3, 'David Ferer', 8, 2);
INSERT INTO tennis_player (id, name, atprank, tournament_id) VALUES (4, 'Andy Murray', 4, 2);
INSERT INTO tennis_player (id, name, atprank, tournament_id) VALUES (5, 'Del Potro', 10, 2);
INSERT INTO tennis_player (id, name, atprank, tournament_id) VALUES (6, 'Novak D', 3, 3);
INSERT INTO tennis_player (id, name, atprank, tournament_id) VALUES (7, 'Marian Cilic', 11, 3);
INSERT INTO tennis_player (id, name, atprank, tournament_id) VALUES (8, 'Milos Raonic', 15, 3);
INSERT INTO tennis_player (id, name, atprank, tournament_id) VALUES (9, 'Borna Coric', 20, 3);
INSERT INTO tennis_player (id, name, atprank, tournament_id) VALUES (10, 'Fabio Fognini', 22, 4);
INSERT INTO tennis_player (id, name, atprank, tournament_id) VALUES (11, 'Karen Khachanov', 25, 4);
INSERT INTO tennis_player (id, name, atprank, tournament_id) VALUES (12, 'Guido Pella', 21, 5);
INSERT INTO tennis_player (id, name, atprank, tournament_id) VALUES (13, 'Denis Shapovalov', 19, 5);
INSERT INTO tennis_player (id, name, atprank, tournament_id) VALUES (14, 'Alex de Minaur', 32, 5);
INSERT INTO tennis_player (id, name, atprank, tournament_id) VALUES (15, 'Lucas Pouille', 34, 5);
INSERT INTO tennis_player (id, name, atprank, tournament_id) VALUES (16, 'Taylor Fritz', 12, 6);
INSERT INTO tennis_player (id, name, atprank, tournament_id) VALUES (17, 'Jeremy Chardy', 40, 6);
INSERT INTO tennis_player (id, name, atprank, tournament_id) VALUES (18, 'Richard Gasquet', 44, 7);
INSERT INTO tennis_player (id, name, atprank, tournament_id) VALUES (19, 'Radu Albot', 42, 7);
INSERT INTO tennis_player (id, name, atprank, tournament_id) VALUES (20, 'Hubert Hurkacz', 13, 7);