INSERT INTO category (id, name) VALUES (1, 'Radio');
INSERT INTO category (id, name) VALUES (2, 'TV');
INSERT INTO category (id, name) VALUES (3, 'MP3');
INSERT INTO category (id, name) VALUES (4, 'Laptop');
INSERT INTO category (id, name) VALUES (5, 'Smartphone');
INSERT INTO product (id, name, category_id) VALUES (1, 'Casio', 1);
INSERT INTO product (id, name, category_id) VALUES (2, 'Myria', 2);
INSERT INTO product (id, name, category_id) VALUES (3, 'HashMusic', 3);
INSERT INTO product (id, name, category_id) VALUES (4, 'Asus', 4);
INSERT INTO product (id, name, category_id) VALUES (5, 'iPhone', 5);
