insert into author (age, name, genre, id) values (23, "Mark Janel", "Anthology", 1);
insert into author (age, name, genre, id) values (43, "Olivia Goy", "Horror", 2);
insert into author (age, name, genre, id) values (51, "Quartis Young", "Anthology", 3);
insert into author (age, name, genre, id) values (34, "Joana Nimar", "History", 4);
insert into book (isbn, title, price, author_id, id) values ("001-JN", "A History of Ancient Prague", 23, 4, 1);
insert into book (isbn, title, price, author_id, id) values ("002-JN", "A People's History", 34, 4, 2);
insert into book (isbn, title, price, author_id, id) values ("001-MJ", "The Beatles Anthology", 55, 1, 3);
insert into book (isbn, title, price, author_id, id) values ("002-MJ", "Anthology Of '99", 44, 1, 4);
insert into book (isbn, title, price, author_id, id) values ("001-OG", "Carrie", 33, 2, 5);
insert into book (isbn, title, price, author_id, id) values ("002-OG", "Last Day", 25, 2, 6);
insert into book (isbn, title, price, author_id, id) values ("003-JN", "History Today", 41, 4, 7);
insert into book (isbn, title, price, author_id, id) values ("003-MJ", "Anthology Of A Game", 21, 1, 8);
